### ISSUE TITLE
Question: Is it possible to get the audio of the call in realtime?

### ISSUE THREAD

**Issue by LeonManolo** [sipgate-io/sipgateio-node#12]
Imagine a scenario with a mute person. We wanted to make an application that allows you
to call any number and answer the callee with pre-recorded audios on button click.
I looked through the API but I'm not sure if it is possible to get the audio of the person the user is calling.
So that he can listen to what the person is saying.

**Comment by paul-siteway** [comment]
@b-squared42 @ramenbox @LukenSkyne @bethgeNetz @ratkowski @MalteSehmer 

Ist hier noch jemand aktiv?

**Comment by nilsreck** [comment]
Hello,

[this API endpoint](https://api.sipgate.com/v2/doc#/rtcm/startCallAnnouncement) offers the opportunity to play announcements to all call participants using [Realtime Call Manipulation](https://api.sipgate.com/v2/doc#/rtcm) (RTCM). Additionally, you can start and stop a recording using [this endpoint](https://api.sipgate.com/v2/doc#/rtcm/setCallRecording). You can find the recorded calls in your account's Event List.

Best regards,
Nils from sipgate.io
