### ISSUE TITLE
Präsenzstatus per API abfragen

### ISSUE THREAD

**Issue by paul-siteway** [sipgate-io/sipgateio-node#16]
Hallo, 

ich würde gerne den **Präsenzstatus** von allen Usern **per API abfragen**. 

Ich würde also gerne abfragen, ob die User mit einem Gerät angemeldet sind und ob Sie gerade telefonieren oder nicht. 
Ich sehe in der [Sipgate Präsenzanzeige](https://app.sipgate.com/w0/presence) Konsole, dass es ähnliche Response gibt: 

Request URL: https://team-de.live.sipgate.com/presence/?key=XXX

```
{
   "phoneState.123456789p23":{
      "phonestate.onphone":true,
      "phonestate.ringing":false,
      "phonestate.incomingRinging":false,
      "phonestate.available":false
   }
}

```
Ich sehe in der Swagger Docs leider nichts dazu: https://api.sipgate.com/v2/doc#/

@b-squared42 @ramenbox @LukenSkyne @bethgeNetz @ratkowski @MalteSehmer @derveloper @jeyemwey @l00kuss @Ahrdie @SvenKube Vielleicht könnt ihr mir einen Tipp gebe, wo ich dazu etwas finde.

**Comment by ThePhoenixCoding** [comment]
Hallo Paul,
ob die Geräte eines Users angemeldet sind, kannst du über den [GET devices](https://api.sipgate.com/v2/doc#/devices/getDevices)-Endpunkt abrufen.

Ob die User eines Accounts gerade telefonieren, ist aus Datenschutzgründen nicht abrufbar. Für deinen eigenen User kann du den Telefonie-Status über den [GET calls](https://api.sipgate.com/v2/doc#/rtcm/getCalls)-Endpunkt abfragen.

Zögere nicht, dich bei Fragen gern erneut an uns zu wenden!

Viele Grüße
Alexa von sipgate.io

**Comment by paul-siteway** [comment]
Hallo Alexa, 

danke für die schnelle Rückmeldung. 

`Ob die User eines Accounts gerade telefonieren, ist aus Datenschutzgründen nicht abrufbar.`
Alle Sipgate User können doch auch über die MeineTelefonie>Präsenzanzeige sehen, wer von den anderen telefoniert. 

Die Clinq-App scheint das ja auch von Sipgate per API abgefragt zu bekommen:
![image](https://user-images.githubusercontent.com/3603487/210810176-bd0621ce-ccd7-4fe4-a07c-d8333ac00ba4.png)

Warum steht dies dann mir als Sipgate(io) User nicht zur Verfügung?

**Comment by ThePhoenixCoding** [comment]
Hallo Paul,
stimmt. Wir haben das Thema nochmal diskutiert und es handelt sich in diesem Fall tatsächlich nicht um eine datenschutzrechtliche, sondern um eine technische Einschränkung, weshalb diese Funktion derzeit über sipgate.io leider nicht öffentlich zur Verfügung steht.

Viele Grüße
Alexa von sipgate.io

**Comment by paul-siteway** [comment]
😭
