### ISSUE TITLE
[Bug] Clean example and documentation of how to send a SMS

### ISSUE THREAD

**Issue by bluepuma77** [sipgate-io/sipgateio-node#18]
**Describe the bug**
Clean example and documentation of how to send a SMS

**To Reproduce**
1. Use [example from Sipgate.io website](https://www.sipgate.io/sms-versenden).
Result: `Error: Invalid extension:` for string "s0".

2. Follow [sigateio-node documentation](https://github.com/sipgate-io/sipgateio-node#sms-1).
```
interface ShortMessage {
	from: string;
	to: string;
	message: string;
}
```
What to put into `from`? Leave it empty? Put "sipgate" into the string? One of my fixed numbers?
Result: `Error: Cannot read properties of undefined (reading 'id')`

3. Wait, there is `getAuthenticatedWebuserId` and `getSmsExtensions`.
Result: `[]`, too bad.

4. Finally there is [sipgateio-node-examples](https://github.com/sipgate-io/sipgateio-node-examples/blob/main/sms/sms_send_phone.ts)
Result with empty `from`: `Error: Cannot read properties of undefined (reading 'id')`

**Expected behavior**
A clear and concise description of how to send a SMS without having a dedicated sender number.

**Environment (please complete the following information):**

- OS: Linux
- Node.js Version: v16.18.1
- Library Version: 2.14.0

**Additional context**

**Comment by ramenbox** [comment]
Hey bluepuma77,

this [example](https://en.sipgate.io/send-sms) worked fine for us with the SMS extension as **s0**. Furthermore, it's not possible to send an SMS without having a dedicated sender number.

Let us know if you've any further inquiries. 

Kind regards

**Comment by bluepuma77** [comment]
Ok, using [a different provider](https://www.sms77.io/en/developer/) now, there you can just enter the sender as string.
