### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by KaySchneider** [sipgate-io/sipgateio-node#7]
**Describe the bug**
  
We used the version: "sipgateio": "^2.1.4", (installed via npm) ,
and BasicAuth to  send Fax via sipgate.io  
 
Today we realised that the sipgate api rejects our calls with 401  
 
We tried different things, but nothing works.   

Only upgrade to the  version "sipgateio": "^2.5.2" and switch to  OAuthCredentials solved our Problem. 
 
My question is, is there a newsletter to get informed about upcoming breaking changes ?  Like removing BasicAuth ;) 
 
Thanks

**Comment by BollSipgate** [comment]
We rolled back the changes regarding the BasicAuth yesterday.
But sticking to OAuth is the way to go and highly recommended.

In the future breaking changes will be better communicated!
